import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
const base=(process.env.REVIEW_URL || 'http://localhost:5173/').replace(/\/$/,'');
await fs.mkdir('test-results',{recursive:true});
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1200},reducedMotion:'reduce'});const page=await context.newPage();const results=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name)}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message.slice(0,400))}}
const viewer=page.getByTestId('storyboard-viewer');
async function open(id,frame=1){await page.goto(`${base}/?direction=${id}&frame=${frame}`);await expect(viewer).toHaveAttribute('data-direction',id);await expect(viewer).toHaveAttribute('data-frame',String(frame));await expect(page.locator('[data-storyboard-review]')).toHaveAttribute('data-ready','true');await viewer.scrollIntoViewIfNeeded()}
await open('horizon');
await check('Thirty directions and 186 scenes',async()=>{await expect(page.getByRole('button',{name:/^Explore \d\d /})).toHaveCount(30);await expect(page.getByText('30 directions / 186 scenes')).toBeVisible()});
await check('Rejected direction and controls absent',async()=>{await expect(page.getByText(/Working Room|Watch OpenSwarm|ONE CONTINUOUS WORKSPACE/i)).toHaveCount(0);await expect(viewer.getByRole('button',{name:/zoom|100%|fullscreen/i})).toHaveCount(0)});
await check('Mega menu opens, previews and closes with Escape',async()=>{await viewer.getByRole('button',{name:'Platform',exact:true}).click();await expect(viewer.getByText('Explore the platform', {exact:true})).toBeVisible();await viewer.getByRole('button',{name:/Your apps and tools Bring/}).hover();await expect(viewer.getByRole('heading',{name:'Your apps and tools'})).toBeVisible();await page.keyboard.press('Escape');await expect(viewer.getByText('Explore the platform', {exact:true})).toHaveCount(0)});
await check('Hero composer advances into the request',async()=>{await viewer.getByRole('textbox',{name:'Sample request'}).fill('Prepare a launch plan from the research');await viewer.getByRole('button',{name:'Run sample request'}).click();await expect(viewer).toHaveAttribute('data-frame','3');await expect(viewer.getByText('The sample is ready. Open the result to continue.')).toBeVisible()});
await check('Canvas/Focus switch retains the result',async()=>{await page.getByRole('group',{name:'Storyboard scenes'}).getByRole('button').nth(3).click();await viewer.getByRole('button',{name:'Focus',exact:true}).click();await expect(viewer.locator('[data-native-pane=conversation]')).toBeHidden();await expect(viewer.locator('[data-native-pane=result]')).toBeVisible();await viewer.getByRole('button',{name:'Canvas',exact:true}).click();await expect(viewer.locator('[data-native-pane=conversation]')).toBeVisible()});
await check('Source tab and actual download',async()=>{await viewer.getByRole('button',{name:'Source',exact:true}).click();await expect(viewer.getByRole('heading',{name:'Source context'})).toBeVisible();const wait=page.waitForEvent('download');await viewer.getByRole('button',{name:'Download sample result'}).click();const download=await wait;expect(download.suggestedFilename()).toBe('Launch plan.md')});
await check('Shortlist persists on reload',async()=>{await page.getByRole('button',{name:'Add to shortlist',exact:true}).click();await page.reload();await expect(page.getByRole('region',{name:'Selected storyboard'}).getByRole('button',{name:'Shortlisted',exact:true})).toHaveAttribute('aria-pressed','true')});
await check('ASCII category filter',async()=>{await page.getByRole('button',{name:'ASCII',exact:true}).click();await expect(page.getByRole('button',{name:/^Explore \d\d /})).toHaveCount(3);await page.getByRole('button',{name:'All',exact:true}).click()});
await open('signal',2);
await check('Selected source updates full preview',async()=>{await viewer.getByRole('button',{name:/Product documentation Document/}).click();await expect(viewer.getByRole('heading',{name:'Product documentation'})).toBeVisible()});
await open('common',2);
await check('Native app library selection',async()=>{await viewer.getByRole('button',{name:/Slack Team conversations/}).click();await expect(viewer.getByRole('heading',{name:'Slack',exact:true})).toBeVisible()});
await open('common',5);
await check('Task app adds and toggles a task',async()=>{await viewer.getByRole('button',{name:'New task',exact:true}).click();const task=viewer.getByRole('button',{name:/Review the next idea/});await task.click();await expect(task).toHaveAttribute('aria-pressed','true');await task.click();await expect(task).toHaveAttribute('aria-pressed','false')});
await open('relay',2);
await check('Workflow status toggles',async()=>{const step=viewer.getByRole('button',{name:/Bring in project context Trigger/});const before=await step.getAttribute('aria-pressed');await step.click();await expect(step).toHaveAttribute('aria-pressed',before==='true'?'false':'true')});
await open('monument',6);
await check('Real Evidence Lab capture selection and scroll',async()=>{await viewer.getByRole('button',{name:'ON Semiconductor case',exact:true}).click();await expect(viewer.getByRole('img',{name:/ON Semiconductor simulation/})).toBeVisible();const pane=viewer.getByRole('region',{name:'Scrollable supplied app capture'});await pane.evaluate(el=>el.scrollTop=350);expect(await pane.evaluate(el=>el.scrollTop)).toBeGreaterThan(100)});
await check('Reduced motion stops scenic autoplay',async()=>{await open('afterglow');expect(await viewer.locator('video').evaluateAll(v=>v.every(x=>x.paused))).toBe(true)});
await check('Explicit native recording playback and pause',async()=>{await open('common',4);await viewer.getByRole('button',{name:'Play native recording'}).click();await expect(viewer.getByRole('button',{name:'Pause native recording'})).toBeVisible();await viewer.getByRole('button',{name:'Pause native recording'}).click();expect(await viewer.locator('video').evaluate(v=>v.paused)).toBe(true)});
await check('Recording pauses when offscreen',async()=>{await viewer.getByRole('button',{name:'Play native recording'}).click();await page.evaluate(()=>scrollTo(0,0));await expect(viewer.locator('video')).toHaveJSProperty('paused',true)});
await check('Sequence advances and stops on interaction',async()=>{await open('horizon');await page.getByRole('button',{name:'Play sequence',exact:true}).click();await expect(viewer).toHaveAttribute('data-frame','2',{timeout:7500});await viewer.getByRole('button',{name:'Close platform menu'}).click();await expect(page.getByRole('button',{name:'Play sequence',exact:true})).toBeVisible()});
await check('Desktop accessibility serious/critical',async()=>{await open('horizon',3);const r=await new AxeBuilder({page}).analyze();await fs.writeFile('test-results/axe.json',JSON.stringify(r.violations,null,2));expect(r.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([])});
await check('Mobile review has no horizontal page overflow',async()=>{await page.setViewportSize({width:390,height:844});await open('afterglow',4);const size=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.w+1);await page.screenshot({path:'test-results/mobile.png'})});
await fs.writeFile('test-results/interactions.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass),errors}));await browser.close();

if(results.some(x=>!x.pass)||errors.length) process.exitCode=1;
